baseURL = "https://moisesEzequiel1.github.io/"
languageCode = "en-us"
title = "Moises Dominguez"
theme = "PaperMod"
buildFuture = true

[params]
  author = "Moises Dominguez"
  description = "CV and Blog of Moises Dominguez"
  showMenu = true
  homeInfoMode = true
  showRecentOnHome = false

[social]
  github = "https://github.com/moisesEzequiel1"
  gitlab = "https://gitlab.com/moisesEzequiel11"
  linkedin = "https://www.linkedin.com/in/moises-ezequiel-dominguez-salcedo-455b771b4/"


[params.homeInfoParams]
Title = "Hi, I'm Moises Dominguez 👋"
Content = """Embedded Software Engineer
Location: Matamoros, Tamaulipas

[View CV](cv/) | [Read Blog](blog/)"""
